var sunshine = true;
var age = 16;
var surname = "zukelwa";
console.log(sunshine);
console.log(typeof sunshine);
console.log(age);
console.log(typeof age);
console.log(surname);
console.log(typeof surname);
var date = new Date();
var fruit = ['apple','banana'];
console.log(date);
console.log(typeof date);
console.log(fruit);
console.log(typeof fruit);
